### ISSUE TITLE
Error with linux x86 version

### ISSUE THREAD

**Issue by Nemoron** [Citrinate/FreePackages#52] opened 2024-09-06 18:19 UTC
The plugin worked fine when I last used asf about a week ago. 
When I tried starting asf today, I get the following error unless I remove the plugin.

ERROR|ASF|InitPlugins() System.TypeLoadException: Could not load type 'System.Diagnostics.DebuggerNonUserCodeAttribute' from assembly 'System.Runtime

[log.txt](https://github.com/user-attachments/files/16911713/log.txt)

**Comment by Citrinate** [comment] 2024-09-06 18:38
Looks like a duplicate of #45.  Make sure you're using the latest version of the plugin: V1.5.2.0

**Closed by Citrinate** 2024-09-06 18:38 UTC

**Comment by Nemoron** [comment] 2024-09-07 08:55
Oh sry. ^^
Btw thank you for your work. :)
